In [1]:
january=march=may=june=31

In [2]:
print(january)

31


In [3]:
print(june)

31


In [4]:
print(january)
print(march)
print (june)

31
31
31


In [6]:
april = 30
june = 30
september = 30
november = 30
january = march = may = july = august = october = december=31
print(september + october)

61


In [7]:
python , java = "data","science"
print(python)
print(java)

data
science


In [8]:
example=5.8

In [9]:
converted_example= int(example)
print(converted_example)

5


In [10]:
number=5

In [14]:
converted_number=float(number)
print(converted_number)

10.3


In [15]:
example2=12

In [16]:
float(example2)

12.0

In [18]:
example3="9A"    #its impossible #any kind of string never converted to intger or float varriable 
int(example3)

ValueError: invalid literal for int() with base 10: '9A'

In [19]:
print(29%7)     #vagsesh

1


In [20]:
print(50%13)     #vagsesh

11


In [21]:
print(9/2)       # devided

4.5


In [22]:
print(9//2)      #reduce of fraction numbner

4


In [23]:
print(11//5)

2


In [24]:
print(2**3)      # 2 to the power 3

8


In [25]:
x= 5
x=x+5
print(x)

10


In [26]:
x=5            
x +=5            #both of same
print(x)

10


In [27]:
varriable=20
varriable -=5
print(varriable)

15


In [28]:
varriable= 4
varriable **=4
print(varriable)

256


In [29]:
name= "my name is shabbir"
print(name)

my name is shabbir


In [37]:
value2= "my name is shabbir \nand my father name is ohab mollek"   #\n function creating new line
print(value2)

my name is shabbir 
and my father name is ohab mollek


In [38]:
value22="hello world \ni am learning data science"
print(value22)

hello world 
i am learning data science


In [39]:
print("i\nlove\npython")

i
love
python


In [40]:
print("i\nlove\tyou")       #\t function  creating distance

i
love	you


In [41]:
print("i\n\nlove\t\tyou")

i

love		you


In [44]:
print("i\blove\tyou")  #confused 

ilove	you


In [49]:
print('i\'m sabbir')

i'm sabbir


In [50]:
"hello" + "data"

'hellodata'

In [61]:
"python" + "" +" is king"

'python is king'

In [63]:
 "hello"*4     #multiple

'hellohellohellohello'

In [65]:
2*"python"*2

'pythonpythonpythonpython'

In [1]:
job="data scientist"
print(len(job))

14


In [3]:
web_address = "www.facebook.com"
web_address.startswith(web_address)

True

In [4]:
p="www.datascience.com"
p.startswith(p)

True

In [6]:
example ="python"
example.startswith(py)

NameError: name 'py' is not defined

In [7]:
example ="python"
example.startswith("py")

True

In [8]:
variable="machine learning"


In [9]:
web_address="www.datascience.com"
web_address.startswith("data",4,8)

True

In [14]:
variable="machine learning"
variable.startswith("ear",9 ,13)

True

In [17]:
web_address = "www.facebook.com"
web_address.endswith(".com")

True

In [18]:
variable = "artificial intelligence"
variable.endswith("ce")

True

In [19]:
sentence= "I live in Dhaka"   #if we are useing (title) keywords thn every wrods first letter showing us with uppercase
sentence.title()

'I Live In Dhaka'

In [21]:
variable ="Data Is The New Oil!"
variable.title()


'Data Is The New Oil!'

In [24]:
variable= "data is the new oil!"   #if we are useing (.swapcase) keyword the every words only first letter become lower case
variable.title().swapcase()

'dATA iS tHE nEW oIL!'

In [26]:
variable33="HELLOW WORLD ,WE ARE INTRODUCING OUR BIG COMPANY BIG DATA"    #done ,its working 
variable33.title().swapcase()

'hELLOW wORLD ,wE aRE iNTRODUCING oUR bIG cOMPANY bIG dATA'

In [28]:
variable="       python    7 "  #(strip) keyword remove any kind of space and letter in any word
variable.strip()

'python    7'

In [32]:
variable = "   shabbir  mollek  "
variable .strip(s)

NameError: name 's' is not defined

In [37]:
variable ="          python app         "     #(strip) keyword working by remove space
variable.strip()

'python app'

In [44]:
space='  python data science '      #confusede 
space.strip().strip("y")

'python data science'

In [45]:
variable="   python app    "
variable.rstrip("p")

'   python app    '

In [50]:
variable = "   python app   "      #(rstrip) this keyword remove righthand space and specefic letter in word 
variable.rstrip().rstrip("thon app")

'   py'

In [51]:
variable = "   python app   "      #(lstrip) this keyword remove lefthand space and specefic letter in word 
variable.lstrip().lstrip("pyt")

'hon app   '

In [52]:
space= "   example  "
dir(space)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [3]:
car = "Ferrari"     #its index calling

car[2]



'r'

In [4]:
car="ferrari"
car[1:5]

'erra'

In [5]:
car="Ferrari"
car[2:6]

'rrar'

In [9]:
car= "Ferrari"
car[2::6]

'r'

In [11]:
variable= "I love python"
variable[6:13]

' python'

In [13]:
variable=" I love Python"
variable[0:10:3]

' ley'

In [18]:
car="ferrari"
print(car[:3])

fer


In [19]:
variable="i love python "
print (variable[:4])

i lo


In [20]:
variable="computer science"
variable[-7]

's'

In [21]:
car="ferrari"
car[-5:-2]

'rra'

In [22]:
variable= "computer science"
variable[-13:-8]

'puter'

In [28]:
nba="shabbir"

nba=nba + "mollik"
print(nba)


shabbirmollik


In [31]:
variable= "Data"
variable=variable + "science"
print(variable)

Datascience


In [32]:
nba="lakers "
nba *=3
print(nba)

lakers lakers lakers 


In [33]:
variable ="python"
variable *=4
print(variable)

pythonpythonpythonpython


In [34]:
element="The atomic number of the element {} is {} ."     #there is called string.format keyword 
print(element.format("Hydrogen" ,1))                     #and that is working on replacing in fixed position on {}

The atomic number of the element Hydrogen is 1 .


In [36]:
element=" The atomic number of the element {} is {} ."  #we are working in this line elememt format by variable thats why we are not useing "" this one 
value1= "Hydrogen"
value2=1
print(element.format(value1 , value2))

 The atomic number of the element Hydrogen is 1 .


In [38]:
value2= 1                          #there is  called f-string methods 
value1="hydrogen"
f"The atomic number of the element {value1} is {value2}."

'The atomic number of the element hydrogen is 1.'

In [39]:
surname="Ador"
f"My surename is {surname.upper()}"

'My surename is ADOR'

In [2]:
list_example2=["berlin","washington",["ankara",100],False]
print(list_example2[3])

False


In [3]:
list_example4=["Rahim","karim",[2,4,6,8],True]
print(list_example4[2])

[2, 4, 6, 8]


In [7]:
list_example4=["Rahim","karim",[2,4,6,8],True]
print(list_example4[2][3])

8


In [8]:
list_example5=["berlin","washington",["ankara",1000],False]
print(list_example5[2][0])

ankara


In [9]:
list_example5=["berlin","washington",["ankara",1000],False]
print(list_example5[0:3])

['berlin', 'washington', ['ankara', 1000]]


In [11]:
int_list=[10,20,39,49,59,73,9827]      #(append)keywords only useing for adding any specefic integer
int_list.append(30)                    
print(int_list)

[10, 20, 39, 49, 59, 73, 9827, 30]


In [16]:
new_list=["germany","india","pakistan","australia","japan"]
new_list.append("russia")
print(new_list)

['germany', 'india', 'pakistan', 'australia', 'japan', 'russia']


In [17]:
new_list=["germany","india","pakistan","australia","japan"]     #(remove) keyword useing for removing or delete specefic equiepment
new_list.remove("india")
print(new_list)

['germany', 'pakistan', 'australia', 'japan']


In [18]:
int_list=[ 10,20,222,456,53,4,5]             #(insert)keywords only useing for equipment specefic postion adding something
int_list.insert(3,3000)
print(int_list)

[10, 20, 222, 3000, 456, 53, 4, 5]


In [21]:
brand=["iphone","samsung","nokia","lg"]
brand.insert(2,"xiaomi")
print(brand)

['iphone', 'samsung', 'xiaomi', 'nokia', 'lg']


In [22]:
int_list=[ 10,20,222,456,53,4,5]             #(pop)keywords only useing for removing specefic position value
int_list.pop(3)
print(int_list)

[10, 20, 222, 53, 4, 5]


In [23]:
int_list=[22,3,33,43,2,33,45,66,4565]     #(sort)keyword its useing for lower to upper numeric number
int_list.sort()
print(int_list)

[2, 3, 22, 33, 33, 43, 45, 66, 4565]


In [24]:
type(int_list)

list

In [25]:
len(int_list)

9

In [26]:
list1="python","java","c++"
print(type(list1))

<class 'tuple'>


In [28]:
new_list=[10,20,"hello","world"]
new_tuple=tuple(new_list)
print(new_tuple)
print(type(new_tuple))

(10, 20, 'hello', 'world')
<class 'tuple'>


In [31]:
list2=["python","java","c++"]
new_tuple=tuple(list2)
print(new_tuple)

('python', 'java', 'c++')


In [44]:
secondary_planet={"earth":"moon",
                 "saturn":"titan",
                 "jupitar":"europa"}
del secondary_palnet["jupitar"]

NameError: name 'secondary_palnet' is not defined

In [11]:
world_cup={"germany": 2006,
              "south africa":2010,
              "brazil":2014,
              "russia":2022}
print(world_cup.items())

dict_items([('germany', 2006), ('south africa', 2010), ('brazil', 2014), ('russia', 2022)])


In [12]:
world_cup={"germany": 2006,
              "south africa":2010,
              "brazil":2014,
              "russia":2022}
world_cup.keys()

dict_keys(['germany', 'south africa', 'brazil', 'russia'])

In [14]:
world_cup={"germany": 2006,               #keys method
              "south africa":2010,
              "brazil":2014,
              "russia":2022}
print(world_cup.keys())

dict_keys(['germany', 'south africa', 'brazil', 'russia'])


In [17]:
world_cup={"germany":"dhaka",               #value method
              "south africa":"cumilla",     #values must be string other output error
              "brazil":"BARISHAL",
              "russia":"SYhlet"}
print(world_cup.values())

dict_values(['dhaka', 'cumilla', 'BARISHAL', 'SYhlet'])


In [21]:
world_cup={"germany":"dhaka",                 #update keyword adding 
           
           "south africa":"cumilla",  
           
           "brazil":"BARISHAL",
           
           "russia":"SYhlet"}
world_cup.update({"bangladesh":"dhafa"})

print(world_cup)

{'germany': 'dhaka', 'south africa': 'cumilla', 'brazil': 'BARISHAL', 'russia': 'SYhlet', 'bangladesh': 'dhafa'}


In [22]:
list1= [22,34,54,56,55,43]        #list converted to set
set1=set(list1)
print(set1)

{34, 43, 55, 54, 22, 56}


In [24]:
set1.add(44455)              #add equiepment in list and converted to set
print(set1)

{34, 44455, 43, 55, 54, 22, 56}


In [25]:
list_example=[5,25,125,25,125]
set1=set(list_example)
set1.add(625)
print(set1)

{25, 125, 5, 625}


In [27]:
list_example=[5,25,125,25,125]
set1=set(list_example)
set1.remove(25)
print(set1)

{125, 5}


In [31]:
list3=[22,33,444,55,66,77,778,88]
set3=set(list3)
set3.remove(444)
set3.remove(33)
set3.remove(77)
print(set3)

{66, 778, 22, 55, 88}


In [33]:
list1=[2,4,6,5,12,11,17]
list2=[1,2,4,5,3,6,7,8,9]
first_set=set(list1)
second_set=set(list2)
first_set.difference(second_set)

{11, 12, 17}

In [34]:
list1=[2,4,6,5,12,11,17]
list2=[1,2,4,5,3,6,7,8,9]
first_set=set(list1)
second_set=set(list2)
second_set.difference(first_set)

{1, 3, 7, 8, 9}

In [2]:
list1=[2,4,6,5,12,11,17]
list2=[1,2,4,5,3,6,7,8,9]
first_set=set(list1)
second_set=set(list2)
second_set.intersection(first_set)

{2, 4, 5, 6}

In [3]:
list1=[2,4,6,5,12,11,17]
list2=[1,2,4,5,3,6,7,8,9]
first_set=set(list1)
second_set=set(list2)

In [4]:
first_set & second_set

{2, 4, 5, 6}

In [5]:
list1=[2,4,6,5,12,11,17]
list2=[1,2,4,5,3,6,7,8,9]
first_set=set(list1)
second_set=set(list2)
second_set.union(first_set)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 17}

In [6]:
list1=[2,4,6,5,12,11,17]                      #there is also code union and another one is and funcyion or keyword
list2=[1,2,4,5,3,6,7,8,9]
first_set=set(list1)
second_set=set(list2)
second_set | first_set

{1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 17}

In [8]:
set_example_1 = set([1,3,5,7])
set_example_2= set([1,2,3,4,5,6,7,8,9,10])
set_example_1 .issubset(set_example_2)

True

In [9]:
print(10>10.3)               #conditional function


False


In [10]:
print(5.85<5.87)

True


In [13]:
print(5.0 == 5)

True


In [14]:
print(5.0 != 5)

False


In [19]:
amount=int(input("please enter the purches amount : "))


if amount > 1500 :
    
    print("You can get 50% discount in our showroom ")

please enter the purches amount : 2500
You can get 50% discount in our showroom 


In [1]:
print (5+8)

13


In [2]:
print("""Welcome to the world most advance email service """)

password= int(input("password : "))

if password =="23456":
    
    print("welcome to our system ")
    
else : 
    
    print("log in failled")
          
    
    
    

Welcome to the world most advance email service 
password : 23456
log in failled


In [5]:
amount=int(input("Enter the your shopping amount: "))
if amount > 1000:
    print("you got the 50% discount")
elif 500 < amount <= 1000:
    print("you get the 255 discount")                #perfect
elif 200 <amount <=499 :  
    print("you get the 10 % discount")
else :
    print("again try")

Enter the your shopping amount: 12000
you got the 50% discount


In [7]:
salary=int(input("please enter your salary: "))

if salary >2000:
    
    print("your new salary: ",salary + (salary* 10/100))
    
elif 1000< salary <=1500:
    
    print("your new salary: ", salary + (salary* 20/100))
    
elif 500 <salary<= 999:
    
    print("your new salary : " ,salary + (salary* 30/100))
    
else :
    print ("your new salary: " ,salary + (salary* 5/100))
    

please enter your salary: 400
your new salary:  420.0


In [8]:
number= [ 1,2,3,4,5]
cubed_number = []

for i in number :
    x=i**3
    cubed_number.append(x)
    
print(cubed_number)    

[1, 8, 27, 64, 125]


In [12]:
number=[1,2,3,4,5,6,7,8,9,10]

even=[]
odd=[]

for i in number :
    if i % 2 ==0:
        even.append(i)
    else:
        odd.append(i)
        
        
print(even)
print(odd)

[2, 4, 6, 8, 10]
[1, 3, 5, 7, 9]


In [13]:
number=[1,2,3,4,5,6,7,8,9,10]
odd=[]

[odd.append(i)for i in number if i % 2 !=0 ]

print(odd)

[1, 3, 5, 7, 9]


In [1]:
import numpy as np


In [2]:
my_list = [-1,0,1]
type (my_list)

list

In [3]:
my_array=np.array(my_list)
my_array

array([-1,  0,  1])

In [4]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9],[4,5,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [4, 5, 9]]

In [6]:
matrix_one= np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 9]])

In [7]:
np.arange(0,100)        #its like that python range 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [11]:
np.arange(0,100,2, dtype =float)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50.,
       52., 54., 56., 58., 60., 62., 64., 66., 68., 70., 72., 74., 76.,
       78., 80., 82., 84., 86., 88., 90., 92., 94., 96., 98.])

In [12]:
list=[0,2,3,4]
list*3

[0, 2, 3, 4, 0, 2, 3, 4, 0, 2, 3, 4]

In [28]:
arr=np.array ([2,3,4,5,6])
arr*2

array([ 4,  6,  8, 10, 12])

In [31]:
np.linspace(1,100,44)

array([  1.        ,   3.30232558,   5.60465116,   7.90697674,
        10.20930233,  12.51162791,  14.81395349,  17.11627907,
        19.41860465,  21.72093023,  24.02325581,  26.3255814 ,
        28.62790698,  30.93023256,  33.23255814,  35.53488372,
        37.8372093 ,  40.13953488,  42.44186047,  44.74418605,
        47.04651163,  49.34883721,  51.65116279,  53.95348837,
        56.25581395,  58.55813953,  60.86046512,  63.1627907 ,
        65.46511628,  67.76744186,  70.06976744,  72.37209302,
        74.6744186 ,  76.97674419,  79.27906977,  81.58139535,
        83.88372093,  86.18604651,  88.48837209,  90.79069767,
        93.09302326,  95.39534884,  97.69767442, 100.        ])

In [35]:
np.linspace(2,222,45,retstep=True)

(array([  2.,   7.,  12.,  17.,  22.,  27.,  32.,  37.,  42.,  47.,  52.,
         57.,  62.,  67.,  72.,  77.,  82.,  87.,  92.,  97., 102., 107.,
        112., 117., 122., 127., 132., 137., 142., 147., 152., 157., 162.,
        167., 172., 177., 182., 187., 192., 197., 202., 207., 212., 217.,
        222.]),
 5.0)

In [40]:
np.linspace(-2,-25,42, retstep=True)

(array([ -2.        ,  -2.56097561,  -3.12195122,  -3.68292683,
         -4.24390244,  -4.80487805,  -5.36585366,  -5.92682927,
         -6.48780488,  -7.04878049,  -7.6097561 ,  -8.17073171,
         -8.73170732,  -9.29268293,  -9.85365854, -10.41463415,
        -10.97560976, -11.53658537, -12.09756098, -12.65853659,
        -13.2195122 , -13.7804878 , -14.34146341, -14.90243902,
        -15.46341463, -16.02439024, -16.58536585, -17.14634146,
        -17.70731707, -18.26829268, -18.82926829, -19.3902439 ,
        -19.95121951, -20.51219512, -21.07317073, -21.63414634,
        -22.19512195, -22.75609756, -23.31707317, -23.87804878,
        -24.43902439, -25.        ]),
 -0.5609756097560976)

In [46]:
np.linspace(1, 2 , 35 ,retstep= True)    #1-d array

(array([1.        , 1.02941176, 1.05882353, 1.08823529, 1.11764706,
        1.14705882, 1.17647059, 1.20588235, 1.23529412, 1.26470588,
        1.29411765, 1.32352941, 1.35294118, 1.38235294, 1.41176471,
        1.44117647, 1.47058824, 1.5       , 1.52941176, 1.55882353,
        1.58823529, 1.61764706, 1.64705882, 1.67647059, 1.70588235,
        1.73529412, 1.76470588, 1.79411765, 1.82352941, 1.85294118,
        1.88235294, 1.91176471, 1.94117647, 1.97058824, 2.        ]),
 0.029411764705882353)

In [47]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [ ]:
import numpy as np

In [4]:
np.zeros((6,6))

NameError: name 'np' is not defined

In [58]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [61]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.eye(1)

array([[1.]])

In [64]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [65]:
np.random.rand(5)

array([0.88627081, 0.02291767, 0.63328064, 0.72725351, 0.64426843])

In [66]:
np.random.rand(4,3)

array([[0.06316326, 0.63844143, 0.91985551],
       [0.27320414, 0.73224957, 0.50836221],
       [0.10527882, 0.75166651, 0.87440329],
       [0.48656887, 0.10321928, 0.59483159]])

In [67]:
np.random.rand(9,8)    #range 0-1

array([[0.56510925, 0.25721785, 0.62643992, 0.50367458, 0.79337823,
        0.77796506, 0.89379223, 0.5012888 ],
       [0.93879491, 0.11314423, 0.06578168, 0.47540122, 0.91596377,
        0.79424331, 0.39482027, 0.16426496],
       [0.39864016, 0.09506938, 0.92267515, 0.24227443, 0.64958205,
        0.14886878, 0.07646928, 0.48634939],
       [0.09730478, 0.17875589, 0.63692027, 0.94560874, 0.28151721,
        0.44234817, 0.30830063, 0.18329575],
       [0.88522234, 0.65995185, 0.30088229, 0.44403449, 0.78412832,
        0.32419118, 0.03675104, 0.03566934],
       [0.69331952, 0.02979653, 0.05768925, 0.47372876, 0.62051185,
        0.76457727, 0.82507796, 0.811977  ],
       [0.240675  , 0.72852629, 0.52595073, 0.552187  , 0.41034855,
        0.44448684, 0.42737656, 0.84407202],
       [0.13742691, 0.89004099, 0.12683837, 0.24711906, 0.72949196,
        0.1636465 , 0.46778768, 0.34862418],
       [0.22958145, 0.66681262, 0.54121992, 0.58792928, 0.01884017,
        0.48819624, 0.359769

In [68]:
np.random.randn(8)      #range +3 to -3

array([-1.81111289,  1.32548624,  1.76527549, -1.10944376, -0.50371996,
       -0.80571577,  0.18522933,  1.11943017])

In [70]:
np.random.randn(11,11)

array([[-9.13721353e-01,  6.80289971e-01, -4.31371774e-01,
         2.97449670e-01,  1.00396594e+00,  4.03326530e-01,
         3.56714305e-01, -8.49910520e-01, -2.20543532e+00,
         1.54662100e-01,  6.91889285e-01],
       [-3.06575005e-01, -5.93932286e-01,  1.57727975e+00,
         1.52897382e+00,  1.12597894e+00,  4.27209080e-01,
        -6.96861818e-01, -2.19433100e-01,  4.18478421e-01,
         1.17467726e+00,  1.79265162e-03],
       [ 3.45437767e-01, -2.26428738e+00, -3.58129477e-01,
        -2.04614882e-01,  2.60244093e-01,  5.55760726e-01,
         4.06130959e-01,  5.22566965e-01, -1.83625531e+00,
         3.33307055e-01,  1.24009475e+00],
       [-1.19952000e+00,  1.64555070e+00,  5.27625961e-02,
         1.09403554e+00, -1.12124428e+00,  1.63725206e+00,
        -1.97268965e+00, -1.52134992e+00,  8.81304610e-01,
        -1.07433659e+00,  3.62617393e-01],
       [ 8.68947180e-01,  4.33867263e-01,  2.05409201e-01,
        -9.54725121e-01,  4.19914320e-02,  4.72214287e-01,
  

In [77]:
np.random.randint(1,20,500)

array([ 1, 16,  3, 11, 14,  4, 15,  2, 10,  4, 15,  2,  3, 13,  9, 16, 17,
       18, 14,  9, 18,  2, 16, 17, 19, 10, 10, 15, 14, 11,  7,  5, 12,  6,
        6,  8, 17, 12,  7,  4, 17,  8,  1,  8, 14, 15,  8, 18, 17,  7, 12,
        7, 13,  6, 12, 18, 15, 19, 19, 18,  6,  9, 14, 19, 16, 17,  8, 13,
       10,  8, 12, 15, 19,  7,  7,  4, 15,  2,  9, 19, 19,  7, 17, 13, 10,
       12, 17, 10, 17,  9,  4,  9, 13,  4,  5, 14,  6, 11,  8, 10, 17,  8,
       15,  9, 13,  7,  5, 10, 16, 17,  8,  6, 10,  5, 14,  8,  9,  2,  1,
       12, 12,  4,  8,  8, 19,  2,  3,  1, 10,  6, 15, 13,  2,  2, 14, 11,
        9, 19,  2, 12,  6, 19, 17,  5,  4, 19, 14, 19,  9,  8, 12,  9,  9,
        4, 16,  5, 17,  7, 11,  7,  6, 15,  2, 10, 19, 16, 14, 11,  3, 18,
        9, 16, 16,  5, 19,  2, 15, 17,  1,  1,  2, 18, 11,  7, 10, 15, 10,
        3, 14, 10, 15,  6,  1,  8, 18,  4,  1, 17, 17, 12,  9, 12, 11,  5,
       12,  7, 14, 10, 17,  8,  4,  5, 11,  6, 14, 13, 15, 14,  4,  7, 18,
       18,  2,  2, 18, 17

Array arrange and reshapping

In [84]:

array_arange = np.arange(16)

In [85]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [91]:
array_randint=np.random.randint(1,200,36)

In [88]:
array_randint

array([  7,  33,  78, 125,  24,  47,  87, 108, 117,  70,  38, 128, 160,
        97,  40, 106, 171, 111,  10, 100,  74,  87, 132,  24, 129, 173,
        50,  77, 140,  57,  62, 153, 122, 141])

In [92]:
array_randint.shape

(36,)

In [94]:
reshape_test=array_randint.reshape(6,6)

In [96]:
reshape_test

array([[ 24,  32, 197, 176, 144, 126],
       [130, 185,  43, 135, 186,  69],
       [128,  86, 179, 160, 158,  29],
       [137,  75,  28, 142,  10,  54],
       [ 84, 116, 179, 109,  90,  49],
       [ 63,  39,  65,  68, 124, 125]])

In [99]:
array_randint.max()

197

In [ ]:
import numpy as np

In [4]:
array_arange=np.arange(25)

NameError: name 'np' is not defined